# This short python script traverses through all directories in the directory "images"
# and creates a list of all files in those subdirectories.
# This list should consist of paths to the files, of the form "images/subdirectory/imagename.jpg".
# Finally, save the list to a txt file, one path per line
# The text file is called images.txt and is used by mribirds.py to load images

# GENERATED BY CHATGPT

import os

def list_files(directory):
    file_list = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            file_path = os.path.join(root, file)
            # Remove leading "images/" from file path
            file_path = file_path.replace(directory + os.sep, "")
            file_list.append(file_path)
    return file_list

def main():
    directory = "images"
    file_list = list_files(directory)
    output_file = "images.txt"
    with open(output_file, 'w') as f:
        for file_path in file_list:
            f.write(file_path + '\n')

if __name__ == "__main__":
    main()